language: rust
cache: cargo
sudo: required
services: docker

rust:
  - stable
  - beta
  - nightly

env:
  - TARGET="x86_64-unknown-linux-gnu"
  - TARGET="mips-unknown-linux-gnu"
  - TARGET="mipsel-unknown-linux-gnu"
  - TARGET="mips64-unknown-linux-gnuabi64"
  - TARGET="mips64el-unknown-linux-gnuabi64"

before_install:
  - cargo install cross

script:
  - cross build --target $TARGET --verbose --all
  - cross test --target $TARGET --verbose --all

matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
  include:
  - rust: stable
    env:
    before_install:
    script:
    - rustup component add rustfmt-preview
    - cargo fmt --all -- --check
